name: CI Básico Laravel (SQLite)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instalar PHP 8.4 y extensiones
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, bcmath, gd, sqlite

      # 3. Instalar Composer 
      - name: Composer Install
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      # 4. Copiar .env y generar APP_KEY
      - name: Copy .env & Generate Key
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate --ansi

      # 5. Ajustar permisos
      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      # 6. Crear base SQLite
      - name: Create SQLite DB
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 7. Instalar ParaTest compatible
      - name: Require ParaTest & Reinstall
        run: |
          composer require --dev brianium/paratest
          composer install --prefer-dist --no-interaction --optimize-autoloader

      # 8. Ejecutar migraciones
      - name: Migrate
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      # 9. Ejecutar tests en paralelo
      - name: Run Tests (parallel)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --parallel

      # 10. Instalar Node.js y compilar assets (opcional)
      - name: Setup Node.js & Build
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          npm ci
          npm run build

      # 11. Subir artefactos de build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: laravel-ci-artifact
          path: |
            vendor/**
            public/build/**
            bootstrap/cache/**
